import java.awt.Container;
import java.awt.GridLayout;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
public class TelaCadastro extends JFrame {
	private JTextField campoNome;
	private JTextField campoDDD;
	private JTextField campoTelefone;
	private JTextField campoEmail;
	private JTextField campoEndereco;
	private JTextField campoNumero;
	private JTextField campoComplemento;
	private JTextField campoBairro;
	private JTextField campoCidade;
	private JTextField campoEstado;
	private JTextField campoCep;
	private JTextField campoCPF;
	private JTextField campoRG;
	private JTextField campoNascimento;
	private JLabel nome;
	private JLabel ddd;
	private JLabel telefone;
	private JLabel email;
	private JLabel endereco;
	private JLabel numero;
	private JLabel complemento;
	private JLabel bairro;
	private JLabel cidade;
	private JLabel estado;
	private JLabel cep;
	private JLabel cpf;
	private JLabel rg;
	private JLabel nascimento;
	public TelaCadastro(String titulo) {
		super(titulo);
		campoNome = new JTextField();
		campoDDD = new JTextField();
		campoTelefone = new JTextField();
		campoEmail = new JTextField();
		campoEndereco = new JTextField();
		campoNumero = new JTextField();
		campoComplemento = new JTextField();
		campoBairro = new JTextField();
		campoCidade = new JTextField();
		campoEstado = new JTextField();
		campoCep = new JTextField();
		campoCPF = new JTextField();
		campoRG = new JTextField();
		campoNascimento = new JTextField();
		nome = new JLabel("Nome:");
		ddd = new JLabel("DDD:");
		telefone = new JLabel("Telefone:");
		email = new JLabel("E-mail:");
		endereco = new JLabel("Endereço:");
		numero = new JLabel("Nº:");
		complemento = new JLabel("Complemento:");
		bairro = new JLabel("Bairro:");
		cidade = new JLabel("Cidade:");
		estado = new JLabel("Estado:");
		cep = new JLabel("Cep:");
		cpf = new JLabel("CPF:");
		rg = new JLabel("RG:");
		nascimento = new JLabel("Nacimento: dd/mm/aa");
	}
	private void mostrarTela() {
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setLocation(150, 300);
		setLayout(new GridLayout(2, 1));
		Container cp = getContentPane();
		JPanel panel = new JPanel();
		panel.setLayout(new GridLayout(4, 4));
		panel.add(nome);
		panel.add(campoNome);
		panel.add(email);
		panel.add(campoEmail);
		panel.add(ddd);
		panel.add(campoDDD);
		panel.add(telefone);
		panel.add(campoTelefone);
		panel.add(endereco);
		panel.add(campoEndereco);
		panel.add(numero);
		panel.add(campoNumero);
		panel.add(complemento);
		panel.add(campoComplemento);
		panel.add(bairro);
		panel.add(campoBairro);
		cp.add(panel);
		JPanel panel2 = new JPanel();
		panel2.setLayout(new GridLayout(2, 6));
		panel2.add(cep);
		panel2.add(campoCep);
		panel2.add(cidade);
		panel2.add(campoCidade);
		panel2.add(estado);
		panel2.add(campoEstado);
		panel2.add(rg);
		panel2.add(campoRG);
		panel2.add(cpf);
		panel2.add(campoCPF);
		panel2.add(nascimento);
		panel2.add(campoNascimento);
		cp.add(panel2);
		pack();
		setVisible(true);
	}
	public static void main(String[] args) {
		TelaCadastro executar = new TelaCadastro("Cadastro de Cliente");
		executar.mostrarTela();
	}
}